config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'pages#index'
  get '/about', to: 'pages#about'
  get '/works', to: 'pages#works'
  get '/skills', to: 'pages#skills'
  get '/articles/create', to: 'articles#create'
  post '/articles/create', to: 'articles#create'
  # get 'pages/index'
  # get 'pages/about'
  # get 'pages/works'
  # get 'articles/create'
  # get 'articles/delete'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_images
  has_one :tech_skill_memo
  enum tag_name: [:top, :work, :skill]
end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  has_one :article, class_name: "article", foreign_key: "article_id"
end

app/models/tech_skill_memo.rb
class TechSkillMemo < ApplicationRecord
  has_one :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def create
    @article = Article.new article_params
    if @article.save
      render :create, notice: 'article was created'

      binding.pry

    else
      render :create, notice: "article wasn't created"

      binding.pry

    end
  end

  def delete
    if @article.delete params[:id]
      render :delete, notice: 'article was created'
    else
      render :delete, notice: 'article was created'
    end
  end

private
  def article_params
    params.permit(:description, :sub_description, :tag_name, :created_at, :updated_at)
  end
end

app/controllers/concerns/load_articles.rb
module LoadArticles
  extend ActiveSupport::Concern

  included do

  end

  def load_articles
    Articles.order(:id).all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  extend LoadArticles
  def index

  end

  def about
    render "about"
  end

  def works
    render "works"
  end

  def skills
    render "skills"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.slim
h1 Articles#create
p Find me in app/views/articles/create.html.slim
= if flash[:notice]
  = flash[:notice]
div.o-form
= form_with(model: @article, url: articles_create_path) do |article|
  div.o-form__textarea
    = article.label(:description, "description")
    = article.text_area(:description, size: "50x10")
  div.o-form__textarea
    = article.label(:sub_description, "sub_description")
    = article.text_area(:sub_description, size: "50x10")
  div.o-form__textarea
    = article.label(:tag_name, "tag_name")
    = article.select(:tag_name, options_for_select(["top", "work", "skill"]))
  = article.fields_for :tech_skill_memo, index: article.object.id do |memo|
    div.o-form__textarea
      = memo.text_area(:url, size: "50x10")
    div.o-form__textarea
      = memo.text_area(:skill_memo, size: "50x10")
      / = hidden_field_tag (:article_id, article.id)
  div.o-form__textarea
    = submit_tag("create")

app/views/articles/delete.html.slim
h1 Articles#delete
p Find me in app/views/articles/delete.html.slim

app/views/layouts/application.slim
doctype html
html
  head
    title
      | MyPortfolio
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'pages/index'

  body.p-home
    = render partial: 'components/header'
    = yield

app/views/pages/about.slim
h2.a-title.-pageTop About
article.o-article
  .a-picture.-circle
    = image_tag  "gixxer1.jpg"
  span.o-article.-aboutContent
    | Touch card 🤗
article.o-article
  div.m-card.-square.-bike
    = image_tag  "gixxer_fl.PNG"
  div.m-card.-square.-game
    = image_tag  "bullet.jpg"
  div.m-card.-square.-spa
    = image_tag  "jelly.gif"
  div.m-card.-square.-github
    = image_tag  "octcat.png"
  div.m-card.-square.-buncho
    = image_tag  "buncho.JPG"
  div.m-card.-square.-flower
    = image_tag  "sakura.jpg"

app/views/pages/index.slim
h2.a-title.-pageTop Welcome to my portfolio!
article.o-article
  = render partial: './components/svg_logo'
  / .a-picture.-circle
  /   = image_tag  "welcom.jpeg"
  span.o-article.-aboutContent
    | Thank you to see my homepage. My name is Kayata, I'm engineer.
    | I have been developing for 3 years. If you want to know me, please check "About".
    | Or you can know about my work from "Works", about developing skill is written at "Skills".
article.o-article.-sec
  div.new-card
  = link_to("/about", class: 'a-link') do
    div.m-card
      div.a-picture
        = image_tag  "gixxer_fl.PNG"
      h2.a-title About
      span.a-title.-middleDesc
        | …かやたについて
      h3.a-title.-desc Show more
  = link_to("/works", class: 'a-link') do
    div.m-card
      div.a-picture
        = image_tag  "person-using-macbook-pro-on-person-s-lap-1181298.jpg"
      h2.a-title Works
      span.a-title.-middleDesc
        | …携わってきた案件について
      h3.a-title.-desc Show more
  = link_to("/", class: 'a-link') do
    div.m-card
      div.a-picture
        = image_tag  "code_fl.JPG"
      h2.a-title Skills
      span.a-title.-middleDesc
        | …スキルセットについて
      h3.a-title.-desc Show more

app/views/pages/skills.slim
h2.a-title.-pageTop Skills
article.o-article
  div.m-card
    div.a-picture
      = image_tag  "woman-in-black-pants-sitting-on-red-metal-railings-3812800.jpg"
    h2.a-title Ruby on Rails
    span.a-title.-sub
      p
        | →2年程度の経験
      p
        | →型を意識せず高速な開発ができますが、設計を誤ると大事故になると思っています。
      p
        | * Railsがやってくれているところの、本質的な勉強をして事故が生まれない方法を身につけていきたい所存です。
    / span.a-title.-sub Show more
  div.m-card
    div.a-picture
      = image_tag  "person-using-macbook-pro-on-person-s-lap-1181298.jpg"
    h2.a-title HTML5 + CSS3
    span.a-title.-sub
      p
        | →3年程度の経験
      p
        | →自分のポートフォリオはオレオレAtomic Designで設計してます。
      p
        | * 修正しやすいように、ページ毎にレイヤーを設けて、部品の調整をするように心がけてます。
  div.m-card
    div.a-picture
      = image_tag  "seo-758264_640.jpg"
    h2.a-title SEO
    span.a-title.-sub
      p
        | →3ヶ月程度の経験
      p
        | →ランキング圏外から、上から2番目までに改善した経験があります。
      p
        | * デザインが与える集客効果は大きく、この経験からデザインを深く学んでいきたいという興味につながっています。
  div.m-card
    div.a-picture
      = image_tag  "sakura.jpg"
    h2.a-title Vue.js / Angular.js(2.x) / jQuery
    span.a-title.-sub
      p
        | →Railsよりも短いくらいの経験
      p
        | →書き方は違えど、実現したいこととコストが若干違うなくらいのテンションで使ってます。
      p
        | ↑異論を歓迎中です。笑
  div.m-card
    div.a-picture
      = image_tag  "buncho.JPG"
    h2.a-title Java, Kotlin
    span.a-title.-sub
      p
        | →Railsよりも短いくらいの経験
      p
        | →型があることへの安心感と、常にメンテナブルな設計の方法を考える機会を与えてくれるので、これからも勉強の機会は見つけていきたい言語です。
      p
        | * Kotlinの方が好きです。
  div.m-card
    div.a-picture
      = image_tag  "sakura2.jpg"
    h2.a-title Other
    span.a-title.-sub
      p
        | →Adobe XDでモックを書いたりしています。
      p.a-title.-mono
        | (Figmaにすればよかった)
      p
        | →どうしてもこのサイトのモックが見たければ
        <a href="https://xd.adobe.com/view/9594aef7-97d4-41c6-5f8a-2ea9c1329bda-e3a5/" class="a-link" target="_blank">こちら</a>
        | を参照してください。
      p
        | * ライブラリを探していると実装したくなっちゃうタイプです。（他人の描いたモックはちゃんと守ります。）

app/views/pages/works.slim
h2.a-title.-workTag  Public
section.o-article data-aos-anchor=".m-card.-start"
  div.m-card.-start data-aos="fade-in" data-aos-offset="0"
    div.a-picture
      = image_tag  "kbs2.png"
    h2.a-title Kitchen Brothers
    h3.a-title.-sub 飲食店向けメディアサイト
    span.a-title.-desc Ruby on Rails5, slim, scss, jQuery...
    / div.m-card data-aos="fade-in" data-aos-offset="0".-workTarget
  div.m-card data-aos="fade-in" data-aos-offset="0"
    div.a-picture
      = image_tag  "order.png"
    h2.a-title Kitchen Brothers365
    h3.a-title.-sub 飲食店向け受発注システム
    span.a-title.-desc Ruby on Rails5, slim, scss, jQuery...
    / div.m-card data-aos="fade-in" data-aos-offset="0".-workTarget
  div.m-card data-aos="fade-in" data-aos-offset="0"
    div.a-picture
      = image_tag  "medcare.png"
    h2.a-title Medcare
    h3.a-title.-sub オンライン診療サービス
    span.a-title.-desc Ruby on Rails5, Angular, Vue.js...

    / div.m-card data-aos="fade-in" data-aos-offset="0".-workTarget

h2.a-title.-workTag  Private
section.o-article
    / div.m-card data-aos="fade-in" data-aos-offset="0".-workTarget
    div.m-card data-aos="fade-in" data-aos-offset="0"
      div.a-picture
        = image_tag  "hanami.png"
      h2.a-title Hanami
      = link_to  "https://github.com/ixap2i/hanami", class: "a-link" do
        / = image_tag  "github.jpg", class: "a-logo -octcat"
        span On GitHub

    / div.m-card data-aos="fade-in" data-aos-offset="0".-workTarget
    div.m-card data-aos="fade-in" data-aos-offset="0"
      div.a-picture
        = image_tag  "andro.png"
      h2.a-title Instagram Sample App
      = link_to  "https://github.com/ixap2i/instagram-sample-app", class: "a-link" do
        / = image_tag  "github.jpg", class: "a-logo -octcat"
        span On GitHub

    / div.m-card data-aos="fade-in".-workTarget
    div.m-card data-aos="fade-in"
      div.a-picture
        = image_tag  "msa.png"
        /  style="background: url(gixxer1.jpg)"
      h2.a-title My Single App
      = link_to  "https://github.com/ixap2i/single-page", class: "a-link" do
        / = image_tag  "github.jpg", class: "a-logo -octcat"
        span On GitHub

    / div.m-card data-aos="fade-in".-workTarget
    div.m-card data-aos="fade-in"
      div.a-picture
        = image_tag  "floap.png"
      h2.a-title Floap
      = link_to  "https://github.com/ixap2i/floap", class: "a-link" do
        / = image_tag  "github.jpg", class: "a-logo -octcat"
        span On GitHub

    div.m-card data-aos="fade-in"
      div.a-picture
        = image_tag  "generics.png"
      h2.a-title ジェネリクスについて
      = link_to  "https://www.slideshare.net/ssuser34abd0/ss-232310580", class: "a-link" do
        span On Slides Share